---
- hosts: ansible-2
  become: yes
  tasks:
  - name: create a file
    file: path=/home/ansible/file.txt state=touch
    notify: first handler
  handlers:
  - name: first handler
    file: path=/home/ansible/handledthis.txt state=touch
